server:
  port: 8081

spring:
  application:
    name: godesii-services

logging:      
  level:
    org.springframework.security: DEBUG

app:
  twilio:
    sid: AC113f85df01c5d6965cd1ed5e739797e6
    token: 9d6b7594eac2c3c1956db43df8685e68
    phoneNo: +17176708304


  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 46000
    refresh-token:
      expiration: 46000
    encryptor:
      password: password
      salt: 626F6F746966756C
